In [1]:
import torch

data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0731, 0.0922],
        [0.3320, 0.2364]]) 



In [2]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [3]:
#By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability)
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
else:
    print("No GPU available")

No GPU available


In [4]:
#Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension. 
# See also torch.stack, another tensor joining operator that is subtly different from torch.cat
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.8064, 0.1396, 0.9125, 0.1835, 0.8064, 0.1396, 0.9125, 0.1835, 0.8064,
         0.1396, 0.9125, 0.1835],
        [0.5929, 0.6565, 0.8312, 0.4525, 0.5929, 0.6565, 0.8312, 0.4525, 0.5929,
         0.6565, 0.8312, 0.4525],
        [0.6276, 0.5532, 0.3984, 0.4206, 0.6276, 0.5532, 0.3984, 0.4206, 0.6276,
         0.5532, 0.3984, 0.4206]])


In [5]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
print('transpose of tensor:', tensor.T)
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

transpose of tensor: tensor([[0.8064, 0.5929, 0.6276],
        [0.1396, 0.6565, 0.5532],
        [0.9125, 0.8312, 0.3984],
        [0.1835, 0.4525, 0.4206]])


tensor([[0.6502, 0.0195, 0.8327, 0.0337],
        [0.3515, 0.4310, 0.6908, 0.2048],
        [0.3939, 0.3060, 0.1587, 0.1769]])

In [6]:
# this computes the natural logarithm of the tensor
# smoothing is used to avoid log(0) ==> like n+1
torch.log(tensor)

tensor([[-0.2152, -1.9690, -0.0915, -1.6954],
        [-0.5227, -0.4208, -0.1849, -0.7930],
        [-0.4658, -0.5920, -0.9202, -0.8661]])

In [7]:
# Broadcasting examples https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics

x=torch.empty(5,7,3)
y=torch.empty(5,7,3)
# same shapes are always broadcastable (i.e. the above rules always hold)

x=torch.empty((0,))
y=torch.empty(2,2)
# x and y are not broadcastable, because x does not have at least 1 dimension

# can line up trailing dimensions
x=torch.empty(5,3,4,1)
y=torch.empty(  3,1,1)
# x and y are broadcastable.
# 1st trailing dimension: both have size 1
# 2nd trailing dimension: y has size 1
# 3rd trailing dimension: x size == y size
# 4th trailing dimension: y dimension doesn't exist

# but:
x=torch.empty(5,2,4,1)
y=torch.empty(  3,1,1)
# x and y are not broadcastable, because in the 3rd trailing dimension 2 != 3

In [9]:
# can line up trailing dimensions to make reading easier
x=torch.empty(5,1,4,1)
y=torch.empty(  3,1,1)
(x+y).size()
torch.Size([5, 3, 4, 1])

# but not necessary:
x=torch.empty(1)
y=torch.empty(3,1,7)
(x+y).size()
torch.Size([3, 1, 7])

x=torch.empty(5,2,4,1)
y=torch.empty(3,1,1)
(x+y).size()

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [10]:
# important difference between torch.tensor and torch.Tensor is that 
# torch.Tensor.dtype is float32 by default, while torch.tensor.dtype is int64
d1 = torch.tensor([1, 2, 3]).dtype
d2 = torch.Tensor([1, 2, 3]).dtype

print(d1, d2)

torch.int64 torch.float32


In [11]:
x = torch.randn(4, 2)
y = x + 1j*x
torch.view_as_complex(x) # simply converts the tensor to complex tensor
torch.view_as_real(y) # simply converts the tensor to real tensor

tensor([[[-0.3821, -0.3821],
         [ 0.2153,  0.2153]],

        [[-1.8665, -1.8665],
         [ 0.8505,  0.8505]],

        [[-1.4508, -1.4508],
         [ 0.2756,  0.2756]],

        [[ 0.5721,  0.5721],
         [ 0.4410,  0.4410]]])

In [ ]:
#torch.outer
#torch.polar