In [7]:
import torch

data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1771, 0.0848],
        [0.1836, 0.7906]]) 



In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [9]:
#By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability)
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
else:
    print("No GPU available")

No GPU available


In [11]:
#Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension. 
# See also torch.stack, another tensor joining operator that is subtly different from torch.cat
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.3113, 0.4934, 0.5368, 0.1463, 0.3113, 0.4934, 0.5368, 0.1463, 0.3113,
         0.4934, 0.5368, 0.1463],
        [0.6478, 0.4330, 0.8947, 0.5336, 0.6478, 0.4330, 0.8947, 0.5336, 0.6478,
         0.4330, 0.8947, 0.5336],
        [0.2687, 0.3853, 0.3881, 0.3062, 0.2687, 0.3853, 0.3881, 0.3062, 0.2687,
         0.3853, 0.3881, 0.3062]])


In [15]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
print('transpose of tensor:', tensor.T)
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

transpose of tensor: tensor([[0.3113, 0.6478, 0.2687],
        [0.4934, 0.4330, 0.3853],
        [0.5368, 0.8947, 0.3881],
        [0.1463, 0.5336, 0.3062]])


tensor([[0.0969, 0.2435, 0.2882, 0.0214],
        [0.4197, 0.1875, 0.8005, 0.2847],
        [0.0722, 0.1485, 0.1507, 0.0938]])

In [ ]:
# Broadcasting examples https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics

>>> x=torch.empty(5,7,3)
>>> y=torch.empty(5,7,3)
# same shapes are always broadcastable (i.e. the above rules always hold)

>>> x=torch.empty((0,))
>>> y=torch.empty(2,2)
# x and y are not broadcastable, because x does not have at least 1 dimension

# can line up trailing dimensions
>>> x=torch.empty(5,3,4,1)
>>> y=torch.empty(  3,1,1)
# x and y are broadcastable.
# 1st trailing dimension: both have size 1
# 2nd trailing dimension: y has size 1
# 3rd trailing dimension: x size == y size
# 4th trailing dimension: y dimension doesn't exist

# but:
>>> x=torch.empty(5,2,4,1)
>>> y=torch.empty(  3,1,1)
# x and y are not broadcastable, because in the 3rd trailing dimension 2 != 3

In [ ]:
# can line up trailing dimensions to make reading easier
>>> x=torch.empty(5,1,4,1)
>>> y=torch.empty(  3,1,1)
>>> (x+y).size()
torch.Size([5, 3, 4, 1])

# but not necessary:
>>> x=torch.empty(1)
>>> y=torch.empty(3,1,7)
>>> (x+y).size()
torch.Size([3, 1, 7])

>>> x=torch.empty(5,2,4,1)
>>> y=torch.empty(3,1,1)
>>> (x+y).size()
RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1